%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/ewenwan/ewenwan/learn/vSLAM/test/vSLAM/ch8/data

# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
number_of_features: 800
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.5
